**Proyecto de Transformaci贸n de Datos en Power BI con Power Query** 

Descripci贸n del Proyecto 
Este proyecto se centra en la transformaci贸n de datos utilizando Power Query en Power BI. El objetivo principal es procesar, consolidar y limpiar archivos ubicados en una carpeta espec铆fica, realizando una serie de transformaciones para facilitar el an谩lisis de datos en el contexto de un an谩lisis de negocios. El script de Power Query se ejecuta en el Editor Avanzado de Power BI y aborda diversas tareas, desde la carga de archivos hasta la eliminaci贸n de duplicados y la manipulaci贸n de fechas.

Desaf铆os Presentados 

Manipulaci贸n de Fechas:
Desaf铆o: Las fechas en los archivos se presentaba sin separadores, en formato yyyymmdd (Ejemplo: 20240103) y algunas estaban incompletas.
Soluci贸n: Se implement贸 una l贸gica para extraer, transformar y combinar partes de las fechas, abordando la variabilidad en el formato y manejando fechas vac铆as.

Manipulaci贸n de Nombres de Archivo:
Desaf铆o: Los nombres de archivo incluyen la fecha de creaci贸n del mismo, por lo que, se requiri贸 extracci贸n y manipulaci贸n para obtener dicha fecha en una nueva columna.
Soluci贸n: Se realizaron varias transformaciones en los nombres de archivo, creando una nueva columna con la fecha de archivo para facilitar el an谩lisis temporal.

Optimizaci贸n del Rendimiento:
Desaf铆o: El procesamiento de grandes conjuntos de datos puede afectar el rendimiento.
Soluci贸n: Se aplic贸 optimizaci贸n al ordenar las filas y utilizar la funci贸n Table.Buffer para luego, eliminar los registros duplicados, manteniendo el registro m谩s reciente y mejorando el rendimiento durante la ejecuci贸n del script.

Normalizaci贸n de Texto:
Desaf铆o: Garantizar la consistencia en el formato del texto, especialmente en nombres de regiones y observaciones.
Soluci贸n: Se aplicaron transformaciones de texto para normalizar may煤sculas y min煤sculas, y para capitalizar correctamente nombres de regiones y observaciones.

Ejecuci贸n del Proyecto 讹
Para ejecutar este proyecto, sigue estos pasos:

El c贸digo detallado es el siguiente:

```
let
    Origen = Folder.Files("E:\Reportes DEM\2024\Reportes_Unificados\OrdenesOrigenAmdocsEmpresas\XLS Procesados\Enero"),
    #"Archivos ocultos filtrados1" = Table.SelectRows(Origen, each [Attributes]?[Hidden]? <> true),
    #"Invocar funci贸n personalizada1" = Table.AddColumn(#"Archivos ocultos filtrados1", "Transformar archivo (4)", each #"Transformar archivo (4)"([Content])),
    #"Columnas con nombre cambiado1" = Table.RenameColumns(#"Invocar funci贸n personalizada1", {"Name", "Source.Name"}),
    #"Otras columnas quitadas1" = Table.SelectColumns(#"Columnas con nombre cambiado1", {"Source.Name", "Transformar archivo (4)"}),
    #"Columna de tabla expandida1" = Table.ExpandTableColumn(#"Otras columnas quitadas1", "Transformar archivo (4)", Table.ColumnNames(#"Transformar archivo (4)"(#"Archivo de ejemplo (4)"))),
    #"Tipo cambiado" = Table.TransformColumnTypes(#"Columna de tabla expandida1",{{"PERIODO", type text}, {"SOURCE_SYSTEM", type text}, {"ORDER_KEY", type text}, {"ORDER_ACTION_KEY", type text}, {"ORDER_ITEM_TYPE_DESC", type text}, {"ORDER_ACTION_STATUS_DESC", type text}, {"ORDER_ACTION_REASON_DESC", type text}, {"ORDER_ACTION_START_DATE", type text}, {"ORDER_ACTION_COMPLETED_DATE", type text}, {"ORDER_ACTION_STEP_TYPE_NAME", type text}, {"CUSTOMER_TYPE_DESC", type text}, {"CUSTOMER_SUB_TYPE_DESC", type text}, {"ENTERPRISE_RUT_ID", type text}, {"IDENTIFICATION_DOCUMENT_1_NUMB", type text}, {"CUSTOMER_LEGAL_NAME", type text}, {"PORTABILITY_TYPE", type text}, {"DELIVERY_METHOD_DESC", type text}, {"CUSTOMER_KEY", type text}, {"SUBSCRIBER_KEY", type text}, {"PRIMARY_RESOURCE_VALUE", type text}, {"PAYMENT_CATEGORY_DESC", type text}, {"AGENT_USER_INITIAL", type text}, {"AGENT_DESC_INITIAL", type text}, {"SALES_CHANNEL_NAME_INITIAL", type text}, {"SALES_SUBCHANNEL_NAME_INITIAL", type text}, {"SITE_NAME_INITIAL", type text}, {"COMPANY_INITIAL", type text}, {"STORE_ID", type text}, {"ID_ORDEN", type text}, {"FECHA_CREACION_ORDEN", type text}, {"FECHA_CREACION_ACTIVIDAD", type text}, {"NOD_NOMBRE_ESTADO", type text}, {"NOD_NOMBRE_OBSERVACION", type text}, {"COMENTARIO_FLAG_ERROR", type text}, {"NOD_REGION", type text}, {"NOD_COMUNA", type text}, {"NOMBRE_CALLE", type text}, {"NUMERO_CALLE", type text}, {"CANTIDAD_ICC", type text}, {"CANTIDAD_IMEI", type text}, {"NOD_ID_ALMACEN_ORIGEN", type text}}),
    #"Filtrando por Cambiar" = Table.SelectRows(#"Tipo cambiado", each ([ORDER_ITEM_TYPE_DESC] = "Cambiar")),
    #"ltimos caracteres insertados" = Table.AddColumn(#"Filtrando por Cambiar", "ltimos caracteres", each Text.End([ORDER_ACTION_START_DATE], 4), type text),
    #"ltimos caracteres insertados1" = Table.AddColumn(#"ltimos caracteres insertados", "ltimos caracteres.1", each Text.End([ltimos caracteres], 2), type text),
    #"Primeros caracteres insertados" = Table.AddColumn(#"ltimos caracteres insertados1", "Primeros caracteres", each Text.Start([ltimos caracteres], 2), type text),
    #"Primeros caracteres insertados1" = Table.AddColumn(#"Primeros caracteres insertados", "Primeros caracteres.1", each Text.Start([ORDER_ACTION_START_DATE], 4), type text),
    #"Personalizada agregada" = Table.AddColumn(#"Primeros caracteres insertados1", "FECHA_INICIO_ACCION_ORDEN", each [ltimos caracteres.1]&"-"&[Primeros caracteres]&"-"&[Primeros caracteres.1]),
    #"ltimos caracteres insertados2" = Table.AddColumn(#"Personalizada agregada", "ltimos caracteres.2", each Text.End([ORDER_ACTION_COMPLETED_DATE], 4), type text),
    #"ltimos caracteres insertados3" = Table.AddColumn(#"ltimos caracteres insertados2", "ltimos caracteres.3", each Text.End([ltimos caracteres.2], 2), type text),
    #"Primeros caracteres insertados2" = Table.AddColumn(#"ltimos caracteres insertados3", "Primeros caracteres.2", each Text.Start([ltimos caracteres.2], 2), type text),
    #"Primeros caracteres insertados3" = Table.AddColumn(#"Primeros caracteres insertados2", "Primeros caracteres.3", each Text.Start([ORDER_ACTION_COMPLETED_DATE], 4), type text),
    #"Personalizada agregada1" = Table.AddColumn(#"Primeros caracteres insertados3", "FECHA_FIN_ACCION_ORDEN", each [ltimos caracteres.3]&"-"&[Primeros caracteres.2]&"-"&[Primeros caracteres.3]),
    #"Reemplazando Fecha Fin Vac铆a por 01-01-1900" = Table.ReplaceValue(#"Personalizada agregada1","--","01-01-1900",Replacer.ReplaceText,{"FECHA_FIN_ACCION_ORDEN"}),
    #"Asignando tipo de dato Fecha" = Table.TransformColumnTypes(#"Reemplazando Fecha Fin Vac铆a por 01-01-1900",{{"FECHA_INICIO_ACCION_ORDEN", type date}, {"FECHA_FIN_ACCION_ORDEN", type date}}),
    #"Texto en min煤sculas" = Table.TransformColumns(#"Asignando tipo de dato Fecha",{{"AGENT_USER_INITIAL", Text.Lower, type text}}),
    #"Poner En May煤sculas Cada Palabra" = Table.TransformColumns(#"Texto en min煤sculas",{{"NOD_NOMBRE_OBSERVACION", Text.Proper, type text}, {"NOD_REGION", Text.Proper, type text}, {"NOD_COMUNA", Text.Proper, type text}, {"NOMBRE_CALLE", Text.Proper, type text}, {"ORDER_ACTION_REASON_DESC", Text.Proper, type text}, {"ORDER_ACTION_STEP_TYPE_NAME", Text.Proper, type text}, {"ORDER_ACTION_STATUS_DESC", Text.Proper, type text}}),
    #"ltimos caracteres extra铆dos" = Table.TransformColumns(#"Poner En May煤sculas Cada Palabra", {{"Source.Name", each Text.End(_, 12), type text}}),
    #"Texto extra铆do antes del delimitador" = Table.TransformColumns(#"ltimos caracteres extra铆dos", {{"Source.Name", each Text.BeforeDelimiter(_, "."), type text}}),
    #"Dividir columna por posiciones" = Table.SplitColumn(#"Texto extra铆do antes del delimitador", "Source.Name", Splitter.SplitTextByPositions({0, 2, 4}), {"Source.Name.1", "Source.Name.2", "Source.Name.3"}),
    #"Tipo cambiado1" = Table.TransformColumnTypes(#"Dividir columna por posiciones",{{"Source.Name.1", type text}, {"Source.Name.2", type text}, {"Source.Name.3", type text}}),
    #"Agregando Fecha de Archivo" = Table.AddColumn(#"Tipo cambiado1", "Fecha_Archivo", each [Source.Name.1]&"-"&[Source.Name.2]&"-"&[Source.Name.3]),
    #"Cambiando a tipo fecha" = Table.TransformColumnTypes(#"Agregando Fecha de Archivo",{{"Fecha_Archivo", type date}}),
    #"Columnas quitadas" = Table.RemoveColumns(#"Cambiando a tipo fecha",{"SOURCE_SYSTEM", "PERIODO", "CUSTOMER_TYPE_DESC", "CUSTOMER_SUB_TYPE_DESC", "IDENTIFICATION_DOCUMENT_1_NUMB", "ENTERPRISE_RUT_ID", "CUSTOMER_LEGAL_NAME", "PORTABILITY_TYPE", "DELIVERY_METHOD_DESC", "SUBSCRIBER_KEY", "PAYMENT_CATEGORY_DESC", "AGENT_DESC_INITIAL", "SALES_CHANNEL_NAME_INITIAL", "SALES_SUBCHANNEL_NAME_INITIAL", "COMPANY_INITIAL", "STORE_ID", "ID_ORDEN", "FECHA_CREACION_ORDEN", "FECHA_CREACION_ACTIVIDAD", "COMENTARIO_FLAG_ERROR", "NOD_ID_ALMACEN_ORIGEN", "ORDER_ACTION_START_DATE", "ORDER_ACTION_COMPLETED_DATE", "ltimos caracteres", "ltimos caracteres.1", "Primeros caracteres", "Primeros caracteres.1", "ltimos caracteres.2", "ltimos caracteres.3", "Primeros caracteres.2", "Primeros caracteres.3", "Source.Name.1", "Source.Name.2", "Source.Name.3", "ORDER_ITEM_TYPE_DESC", "CUSTOMER_KEY", "PRIMARY_RESOURCE_VALUE", "SITE_NAME_INITIAL", "NOD_NOMBRE_ESTADO", "CANTIDAD_ICC", "CANTIDAD_IMEI"}),
    #"Filas ordenadas" = Table.Buffer(Table.Sort(#"Columnas quitadas",{{"Fecha_Archivo", Order.Descending}})),
    #"Duplicados quitados" = Table.Distinct(#"Filas ordenadas", {"ORDER_ACTION_KEY"})
in
    #"Duplicados quitados"
```

Conclusiones 
Este proyecto ilustra la potencia de Power Query en Power BI para la limpieza y transformaci贸n efectiva de datos. La combinaci贸n de funciones personalizadas, manipulaci贸n de fechas y optimizaci贸n de rendimiento aborda desaf铆os comunes en la preparaci贸n de datos para el an谩lisis posterior. El resultado es una tabla estructurada y lista para ser utilizada en informes y visualizaciones dentro de Power BI.
